import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <div className="flex flex-col min-h-screen mx-auto max-w-screen-2xl">
            <Header />
            <main className="flex flex-1">{children}</main>
            <Footer />
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
